x-app: &app
  build:
    context: ./admin
  image: cfm-auth-app
  env_file: .env
  environment:
    POSTGRES_HOST: db
    POSTGRES_PORT: "5432"
  volumes:
    - ./admin:/app          # faqat development uchun
  networks:
    - cfm_network
  restart: unless-stopped

services:
  db:
    image: postgres:16-alpine
    container_name: cfm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - cfm_network

  web:
    <<: *app
    container_name: cfm_web
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    command:
      - sh
      - -c
      - |
        set -e
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput
        python manage.py createsuperuser --noinput || true
        exec python manage.py runbolt --host 0.0.0.0 --port 8888 --processes 2

  bot:
    <<: *app
    container_name: cfm_bot
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
    command: python manage.py runbot

volumes:
  postgres_data:

networks:
  cfm_network:
    driver: bridge